name: CI Tests
on: [pull_request]
jobs:
  check-linter:
    name: check golang linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
  check-format:
    name: check golang format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - run: make check-format
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - run: make test
